odin-flight-booker/config/routes.rb
Rails.application.routes.draw do

  get 'flights' => 'flights#index'
  get 'params[:id]' => 'bookings#show'

  resources :bookings, only: [:new, :create, :show]

  root 'flights#index'

end

odin-flight-booker/app/models/airport.rb
class Airport < ActiveRecord::Base
	has_many :departing_flights,	class_name: "Flight",
																foreign_key: "from_airport_id",
																dependent: :destroy
	has_many :arriving_flights, 	class_name: "Flight",
																foreign_key: "to_airport_id",
																dependent: :destroy
end

odin-flight-booker/app/models/booking.rb
class Booking < ActiveRecord::Base
	has_many :passengers,	dependent: :destroy
	belongs_to :flight
	accepts_nested_attributes_for :passengers
end

odin-flight-booker/app/models/flight.rb
class Flight < ActiveRecord::Base
	belongs_to :to_airport,		class_name: "Airport"
	belongs_to :from_airport,	class_name: "Airport"
	has_many :bookings,				dependent: :destroy
end

odin-flight-booker/app/models/passenger.rb
class Passenger < ActiveRecord::Base
	belongs_to :booking
end

odin-flight-booker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

odin-flight-booker/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
  	if request.original_url.include?("?")
			flight_pos = request.original_url.index("flight_id") + 13
			i = 0
			i += 1 while request.original_url[flight_pos+i] =~ /\d/
			i -= 1
			flight_id = request.original_url[flight_pos..flight_pos+i]
			@flight = Flight.find(flight_id)
			pass_pos = request.original_url.index("num_of_pass") + 15
			@num_of_pass = request.original_url[pass_pos].to_i
		end
		@booking = Booking.new
		@passenger = Passenger.new
		@num_of_pass.times { @booking.passengers.build }
  end

  def create
  	@booking = Booking.new(booking_params)
  	respond_to do |format|
			if @booking.save
				@booking.passengers.each do |p|
					PassengerMailer.thank_you_email(p).deliver_later
				end
				format.html { redirect_to(@booking, notice: "Booking was successfully created!") }
				format.json { render json: @booking, status: :created, location: @booking}
			else
				format.html { render :new }
				format.json { render json: @booking.errors, status: :unprocessable_entity }
			end
		end
  end

  def show
  	@booking = Booking.find(params[:id])
  	@flight = @booking.flight
  	@passengers = @booking.passengers
  end

  private

  	def booking_params
  		params.require(:booking).permit(:flight_id, :number_of_passengers,
  																		passengers_attributes: [:id, :name, :email])
  	end
end

odin-flight-booker/app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
  	@airport_options = Airport.all.map{ |a| a.code }
  	@flights = Flight.all
  	@number_of_passengers = [1,2,3,4]
  	@dates = []
  	Flight.all.each do |flight|
  		unless @dates.include?(flight_date = flight.start_datetime.strftime("%m/%d/%Y"))
				@dates << flight_date
			end
			@dates.sort!
  	end
  	@booking = Booking.new
  	if request.original_url.include?("?")
			from_pos = request.original_url.index("from_code") + 13
			from_code = request.original_url[from_pos..from_pos+2]
			@from_airport = Airport.find_by(code: from_code)
			to_pos = request.original_url.index("to_code") + 11
			to_code = request.original_url[to_pos..to_pos+2]
			@to_airport = Airport.find_by(code: to_code)
			pass_pos = request.original_url.index("num_of_pass") + 15
			@num_of_pass = request.original_url[pass_pos].to_i
			month_pos = request.original_url.index("date") + 8
			month = request.original_url[month_pos..month_pos+1].to_i
			day = request.original_url[month_pos+5..month_pos+6].to_i
			year = request.original_url[month_pos+10..month_pos+13].to_i
			@date = DateTime.new(year, month, day)
			@selected_flights = []
		end
  end
end

odin-flight-booker/app/helpers/application_helper.rb
module ApplicationHelper
end

odin-flight-booker/app/helpers/bookings_helper.rb
module BookingsHelper
end

odin-flight-booker/app/helpers/flights_helper.rb
module FlightsHelper
end

odin-flight-booker/app/views/bookings/new.html.erb
<h1>New Booking</h1>

<h3>Flight information</h3>
Flight ID:
<strong><%= @flight.id %></strong>
<br>
Date & Time:
<strong><%= @flight.start_datetime.strftime("%m/%d/%Y") %>, <%= @flight.start_datetime.strftime("%I:%M%p") %></strong>
<br>
From:
<strong><%= @flight.from_airport.code %></strong> | To:
<strong><%= @flight.to_airport.code %></strong>
<br>

<h3>Passenger information</h3>
<%= form_for @booking do |f| %>
	<%= f.hidden_field(:flight_id, :value => @flight.id) %>
	<%= f.hidden_field(:number_of_passengers, :value => @num_of_pass) %>
	<% i = 1 %>
	<%= f.fields_for :passengers do |passenger_form| %>
		<h4>Passenger <%= i %></h4>
		<%= passenger_form.label :name %>
		<%= passenger_form.text_field :name %>

		<%= passenger_form.label :email %>
		<%= passenger_form.email_field :email %>
		<% i += 1 %>
		<br><br>
	<% end %>
	<%= f.submit "Create booking" %>
<% end %>

odin-flight-booker/app/views/bookings/show.html.erb
<h1>Booking #<%= @booking.id %></h1>

Flight ID:
<strong><%= @booking.flight.id %></strong>
<br>
Date & Time:
<strong><%= @booking.flight.start_datetime.strftime("%m/%d/%Y") %>, <%= @booking.flight.start_datetime.strftime("%I:%M%p") %></strong>
<br>
From:
<strong><%= @booking.flight.from_airport.code %></strong> | To:
<strong><%= @booking.flight.to_airport.code %></strong>
<br>

<h3>Passenger Information</h3>
<% i = 1 %>
<% @booking.passengers.each do |passenger| %>
	<h4>Passenger <%= i %></h4>
	Name:
	<strong><%= passenger.name %></strong>
	<br>
	Email:
	<strong><%= passenger.email %></strong>
	<br><br>
	<% i += 1 %>
<% end %>

odin-flight-booker/app/views/flights/index.html.erb
<h1>Flights</h1>
<%= form_for('/flights', method: :get) do |f| %>
	Departing from: <%= f.select(:from_code, @airport_options) %>
	Arriving at: <%= f.select(:to_code, @airport_options) %>
	Number of passengers: <%= f.select(:num_of_pass, @number_of_passengers) %>
	Date: <%= f.select(:date, @dates) %>
	<%= f.submit "Search" %>
<% end %>
<% if request.original_url.include?("?") %>
	<h3>Results:</h3><br>
	<% @flights.each do |flight| %>
		<% if flight.from_airport == @from_airport && flight.to_airport == @to_airport && flight.start_datetime.beginning_of_day == @date %>
			<% @selected_flights << flight %>
		<% end %>
	<% end %>
	<% if @selected_flights.empty? %>
		<h4><i>No results found</i></h4>
	<% else %>
		<%= form_for('bookings/new', url: new_booking_path, html: {method: :get}) do |f| %>
			<%= f.hidden_field(:num_of_pass, :value => @num_of_pass) %>
			<% @selected_flights.each do |flight| %>
					<%= f.radio_button :flight_id, flight.id %>
					<%= "From: #{flight.from_airport.code} | To: #{flight.to_airport.code} | Date & Time: #{flight.start_datetime.strftime("%m/%d/%Y")}, #{flight.start_datetime.strftime("%I:%M%p")}" %>
					<br>
			<% end %>
			<%= f.submit "Choose flight" %>
		<% end %>
	<% end %>
<% end %>

odin-flight-booker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinFlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>